# Generated by Django 2.2.10 on 2021-10-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211005_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='uuid',
            new_name='anonuser_id',
        ),
    ]
